### PR TITLE
Added extra log messages so progress of cleaning can be monitored.

### PR DESCRIPTION
**Pull request by demiankatz**
Not sure if we want this on by default or if it should be controlled by a switch, but I find this useful for troubleshooting, so I figured I would share it.

### CODE REVIEW

**Comment by jpstroop** [comment]
@demiankatz :arrow_up: I must have merged in the wrong order 😦

**Comment by demiankatz** [comment]
Hopefully not too hard to fix -- I'll sort it out after the conference. Thanks!

**Comment by demiankatz** [comment]
@jpstroop, the conflict is now resolved, so this should merge cleanly again. Thanks!

**Comment by jpstroop** [comment]
:+1:

**Pull request merged**
