### PR TITLE
tests.py should not return 0 on fail

### PR DESCRIPTION
**Pull request by jpstroop**
Possible fix for #247

### CODE REVIEW

**Comment by jpstroop** [comment]
Yay, it failed!

**Comment by jpstroop** [comment]
I'm going to merge...may as well advertise the truth.

**Review by jrhoads — COMMENTED** [review]
Looks good.  We were heading to this solution as well.
Thanks for the quick fix.

Question: Should we keep the verbosity so high for the tests we send to travis?  It seems a shame that we cannot view the error in the travis web view of the log.

**Comment by jpstroop** [comment]
> Should we keep the verbosity so high for the tests we send to travis? It seems a shame that we cannot view the error in the travis web view of the log.

I'm happy to have to volume turned down.

**Comment by jpstroop** [comment]
I think this may be why that `test.sh` script existed, now that I think about it.

**Pull request merged**
