### PR TITLE
Catch hanging openjpeg transforms

### PR DESCRIPTION
**Pull request by bcail**

### CODE REVIEW

**Review by alexwlchan — COMMENTED** [review]
Do you have an example of an OpenJPEG transform that hangs? Could we check that in tests somehow?

**Comment by bcail** [comment]
Well, it could hang if there's a library missing so the executable won't run. Another possibility might be an invalid JP2 image, an image that's not actually JP2. I'll work on some testing.

**Comment by bcail** [comment]
@alexwlchan I rebased this branch, and added a couple tests for terminating an OpenJPEG or Kakadu transform process if the timeout expires.

**Review by alexwlchan — APPROVED** [review]
Okay, looks good with tests. Merge when you’re ready. 👍

**Pull request merged**
