### PR TITLE
Handles JP2 files with colr METH values 3 & 4

### PR DESCRIPTION
**Pull request by jchristo4**
This PR enables decoding/rendering of JP2 files with colr `METH` values > 2 after validating `PREC` and `APPROX` values. Following Table M.24 from JP2 spec lists legal values for Colour specification box field values - 

image

### CODE REVIEW

**Comment by jpstroop** [comment]
Thanks Chris! I'll get to this tomorrow morning.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

**Comment by jpstroop** [comment]
Interesting...do you still have your copy of the JP2 spec at hand? I'm curious to know the version. The version I'm working from is "ISO/IEC 15444-1 INTERNATIONAL STANDARD; Second edition 2004-09-15" or "ISO/IEC 15444-1:2004(E)" That table in this version looks like this:

screenshot from 2015-03-10 10 44 17

I have a feeling I'm due for an update!

**Comment by jchristo4** [comment]
@jpstroop Copy of the JP2 spec I used was [ISO/IEC 15444-2:2004(E)](http://wiki.opf-labs.org/download/attachments/11337812/15444-2annexm.pdf?version=1&modificationDate=1324487560000) from [OPF Knowledge Base Wiki](http://wiki.opf-labs.org/display/TR/Files+identified+as+JP2+are+really+JPX). Looks like the document is an annex  (JPEG 2000 Part 2). 

Not sure our JP2 files with METH 3 are JPX (JP2 Part 2) files. `Brand` value is `jp2` in them. 

Snippet from METH 3 JP2 file header - 

```
GROUP = ftyp
    Name = File_Type
    Type = 16#66747970#
    ^Position = 12 <byte offset>
    Length = 28 <bytes>
    Brand = "jp2 "
    Minor_Version = 0
    Compatibility = 
        {"jp2 ", jpxb, "jpx "}
END_GROUP
```

**Comment by jpstroop** [comment]
Ah, interesting. JPX files are ringing a bell. I'd have to ask our 
imaging studios, but I want to say that Photoshop produced them back in 
the days when it was part of our workflow, and I think the main reason 
for it was so that they could use or embed the Adobe 1998 color 
profile...or something along those lines.

Anyway, thanks for the info and the PR! You may have noticed that the 
setup.py script changed pretty significantly yesterday. Docs should be 
up to date, but I hope it's not causing you too much trouble.

-Js

**Comment by jchristo4** [comment]
@jpstroop That makes sense. METH 3 JP2s have Adobe RGB (1998) as color profile. Maybe, Photoshop was used to create/correct these JP2s. 

```
<colourSpecificationBox>
    <meth>Any ICC</meth>
    <prec>2</prec>
    <approx>1</approx>
    <icc>
        <profileSize>560</profileSize>
        <preferredCMMType>ADBE</preferredCMMType>
        <profileVersion>2.1.0</profileVersion>
        <profileClass>Display Device Profile</profileClass>
        <colourSpace>RGB </colourSpace>
        <profileConnectionSpace>XYZ </profileConnectionSpace>
        <dateTimeString>1999/06/03, 00:00:00</dateTimeString>
        <profileSignature>acsp</profileSignature>
        <primaryPlatform>Apple Computer, Inc.</primaryPlatform>
        <embeddedProfile>no</embeddedProfile>
        <profileCannotBeUsedIndependently>no</profileCannotBeUsedIndependently>
        <deviceManufacturer>none</deviceManufacturer>
        <deviceModel/>
        <transparency>Reflective</transparency>
        <glossiness>Glossy</glossiness>
        <polarity>Positive</polarity>
        <colour>Colour</colour>
        <renderingIntent>Media-Relative Colorimetric</renderingIntent>
        <connectionSpaceIlluminantX>0.9642</connectionSpaceIlluminantX>
        <connectionSpaceIlluminantY>1.0</connectionSpaceIlluminantY>
        <connectionSpaceIlluminantZ>0.8249</connectionSpaceIlluminantZ>
        <profileCreator>ADBE</profileCreator>
        <profileID>00000000000000000000000000000000</profileID>
        <tag>cprt</tag>
        <tag>desc</tag>
        <tag>wtpt</tag>
        <tag>bkpt</tag>
        <tag>rTRC</tag>
        <tag>gTRC</tag>
        <tag>bTRC</tag>
        <tag>rXYZ</tag>
        <tag>gXYZ</tag>
        <tag>bXYZ</tag>
        <description>Adobe RGB (1998)</description>
    </icc>
</colourSpecificationBox>
```

**Comment by jpstroop** [comment]
I'd say that's a good guess! Thanks again.

**Pull request merged**
