### PR TITLE
Refactor dissect uri

### PR DESCRIPTION
**Pull request by bcail**

### CODE REVIEW

**Comment by jpstroop** [comment]
@bcail Have you tried this behind a real server? I imagine it's OK, but so much of the backflipping here (years ago) was only evident when running with Apache, it would be good to double check that it still works.

**Comment by bcail** [comment]
I'll test it behind apache, and also fix the conflicts.

**Comment by jpstroop** [comment]
:+1:

**Comment by bcail** [comment]
Updated the PR. Tried it out in our dev environment, found a problem, fixed it (with a test), and then it worked fine. Haven't done a lot of testing, but initial use in our dev environment is fine now.

**Comment by jpstroop** [comment]
Thanks!

**Pull request merged**
