### PR TITLE
Fixed subclass relationship in TemplateHTTPResolver. (#239)

### PR DESCRIPTION
**Pull request by peichman-umd**
Eliminated duplicate code by correcting the call to the superclass **init** method in TemplateHTTPResolver.

Fix for #239

### CODE REVIEW

**Comment by jpstroop** [comment]
@rlskoeser and @ghukill it would be good to know if this was a bug or intentional for some reason I'm missing.

**Comment by ghukill** [comment]
Thanks for the heads up.  My contributions were small, and post-creation of the `TemplateHTTPResolver`,  so while I can't speak to the original designs, looks like it makes sense.  Might explain why we needed to [pull in a particular config parameter](https://github.com/loris-imageserver/loris/commit/076e863ed3c289956fb09d6bb72791dbd61be517#diff-0e4e711cf8f48f97f21ec34c7e8351a9) at one point?

**Comment by peichman-umd** [comment]
@ghukill Yeah, I was able to strip out a bunch of code in the initializer that was copied from the SimpleHTTPResolver.**init** method. We should also be able to remove the line you point to as well.

**Comment by rlskoeser** [comment]
Went back to the original pull request (#164) to look.  The only thing I can think of is that perhaps I was intentionally skipping the irrelevant configurations that are initialized in the SimpleHTTPResolver, and/or avoiding the error handling that doesn't apply to the template config.  (Clearly I should have added a comment to that effect if it _was_ intentional, since it's really not obvious.)

It seems like there might be a more elegant way to handle loading variant configs in subclasses than the way this is implemented, but if it works with the change then it sounds like it's not a problem.  (It looks like setting the `uri_resolvable` flag avoids the error that otherwise would have been raised.)

**Comment by peichman-umd** [comment]
@rlskoeser By variant configs do you mean things like varying not just the URL template but also the user credentials or ssl_verify status based on which template is selected? If so, I also have changes to address that, which I will be submitting. If not, I'd be interested to hear what you are thinking about in terms of variation.

**Comment by peichman-umd** [comment]
To elaborate a bit more on the enhancements for switch request options based on selected template, what I have done is created subsections of the `[resolver]` section named after each template, and placed custom request option settings (e.g., `user`, `pw`) in there. The main change in the code is to make the retrieval of the request options dynamic in the TemplateHTTPResolver. I did this by changing the `_web_request_url` method to return a tuple of `(url, options)` instead of just the URL.

I am waiting to see the resolution of this PR before submitting those changes, since it does depend on the TemplateHTTPResolver calling the SimpleHTTPResolver initializer.

**Pull request merged**
