### PR TITLE
remove unused favicon code

### PR DESCRIPTION
**Pull request by bcail**

### CODE REVIEW

**Comment by jpstroop** [comment]
This does get used whenever an image is requested directly; not very often, obviously, but it keeps errors out of the logs.

**Comment by bcail** [comment]
I'm not seeing what URL would result in params == 'favicon.ico', so that get_favicon() gets called. If you give me an example, I can add a test for it.

**Comment by jpstroop** [comment]
Hmm, you're right, looks broken. I'm seeing entries like this in my logs:

```
[23/Sep/2016:14:32:11 -0400] "GET /favicon.ico HTTP/1.1" 404 574 "https://libimages1.princeton.edu/loris/ex.jp2/info.json" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.116 Safari/537.36"
```

**Comment by jpstroop** [comment]
It may just need to be `ident == 'favicon.ico'`.

The next version of Loris **will not** use WSGI for reasons like this (not this in particular, but how difficult the fact that URLs are automatically decoded makes routing).

**Comment by bcail** [comment]
I can close this PR and submit another one that fixes it and has a test.

**Comment by jpstroop** [comment]
Thanks!

**Pull request closed without merging**
